// 規格範例報告，僅供 staging 尚未可用時預覽畫面，數值為示意；結構同 POC 回應的 report。
const sampleReportJson = <String, dynamic>{
  'overall': {'score': 78},
  'summary': '本次痘痘與眼袋狀況較佳，斑點與黑眼圈是較值得持續留意的項目。',
  'dimensions': [
    {
      'code': 'wrinkles',
      'name': '皺紋',
      'order': 1,
      'kind': 'score',
      'score': 82,
      'category': null,
      'explanation': '眼尾可見少量細紋，紋路較淺；額頭與眉間沒有明顯的深紋。',
    },
    {
      'code': 'pores',
      'name': '毛孔',
      'order': 2,
      'kind': 'score',
      'score': 76,
      'category': null,
      'explanation': '鼻翼及鼻子兩側的臉頰可見毛孔，主要集中在靠近鼻子的區域，外側臉頰較不明顯。',
    },
    {
      'code': 'acne',
      'name': '痘痘',
      'order': 3,
      'kind': 'score',
      'score': 84,
      'category': null,
      'explanation': '下巴可見零星痘痘，分布範圍小，兩頰與額頭未見密集的痘痘。',
    },
    {
      'code': 'spots',
      'name': '斑點',
      'order': 4,
      'kind': 'score',
      'score': 72,
      'category': null,
      'explanation': '兩頰可見散在的深色斑點，顏色比周圍膚色深，顴骨附近較明顯。',
    },
    {
      'code': 'dark_circles',
      'name': '黑眼圈',
      'order': 5,
      'kind': 'score',
      'score': 70,
      'category': null,
      'explanation': '雙眼下方的顏色比周圍膚色深，從內眼角延伸到下眼瞼中段，與兩頰形成明顯色差。',
    },
    {
      'code': 'eye_bags',
      'name': '眼袋',
      'order': 6,
      'kind': 'score',
      'score': 84,
      'category': null,
      'explanation': '下眼瞼有輕微隆起，範圍較小，沒有明顯向下延伸的袋狀輪廓。',
    },
  ],
};
